/**:
  ros__parameters:
    # Output frame ids
    pose_frame_id: "map"
    child_frame_id: "base_link"

    # EKF (same structure as ekf_localizer for compatibility)
    node:
      predict_frequency: 50.0
      enable_yaw_bias_estimation: true
      extend_state_step: 50

    pose_measurement:
      pose_additional_delay: 0.0
      pose_gate_dist: 49.5
      pose_smoothing_steps: 5
      max_pose_queue_size: 5

    twist_measurement:
      twist_additional_delay: 0.0
      twist_gate_dist: 46.1
      twist_smoothing_steps: 2
      max_twist_queue_size: 2

    process_noise:
      proc_stddev_vx_c: 10.0
      proc_stddev_wz_c: 5.0
      proc_stddev_yaw_c: 0.005

    simple_1d_filter_parameters:
      z_filter_proc_dev: 5.0
      roll_filter_proc_dev: 0.1
      pitch_filter_proc_dev: 0.1

    # Stop filter
    stop_filter:
      linear_x_threshold: 0.1
      angular_z_threshold: 0.02

    # Twist2Accel
    twist2accel:
      accel_lowpass_gain: 0.2
